name: Run Selenium Test

on:
  push:
    branches: ["master"]
  schedule:
    - cron: "0 8 * * 0-4"  # Run at 10:00 AM from Sunday to Thursday

jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: "21"
          cache: maven
          distribution: "adopt"

      - name: Set up Chrome browser
        uses: browser-actions/setup-chrome@latest

      - name: Run Selenium Tests and Generate Report
        run: |
          mvn clean test -Denvironment=ip
        continue-on-error: true

      - name: Archive artifacts
        id: generate-report
        uses: actions/upload-artifact@v2
        with:
          name: test-reports
          path: target/surefire-reports/

  send-email:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: test-reports
          path: target/surefire-reports

      - name: Check test results
        id: check-test-results
        run: |
          failures=$(awk '/Tests run:/ && /Failures: [1-9]+/ {print "Failures found"}' target/surefire-reports/*.txt || true)
          echo "::set-output name=test-failures::$failures"

      - name: Send email on failure
        if: ${{ steps.check-test-results.outputs.test-failures != '' }}
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: ${{ secrets.EMAIL_SERVER }}
          server_port: ${{ secrets.EMAIL_PORT }}
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          to: "aabdelaziz@azka.com"
          from: "azkatestingteam@gmail.com"
          subject: "Khadem Store Test Results - Failure"
          body: |
            <p>
            Dear Eng. Ahmed,
            The Selenium test results indicate a failure. Please review the attached HTML report.
            </p>
          attachments: target/surefire-reports/emailable-report.html

      - name: Send email on success
        if: ${{ steps.check-test-results.outputs.test-failures == '' }}
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: ${{ secrets.EMAIL_SERVER }}
          server_port: ${{ secrets.EMAIL_PORT }}
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          to: "aabdelaziz@azka.com, mrashwan@azka.com"
          from: "azkatestingteam@gmail.com"
          subject: "Khadem Store Test Results - Success"
          body: |
            <p>
            Dear Eng. Ahmed,
            The Selenium test results indicate a success. Please find the attached HTML report.
            </p>
          attachments: target/surefire-reports/emailable-report.html