name: Run Selenium Test

on:
  push:
    branches: ["master"]
  schedule:
    - cron: "0 8 * * 0-4"  # Run at 10:00 AM from Sunday to Thursday

jobs:
  test:
    runs-on: windows-latest
    strategy:
      matrix:
        java-version: ['21']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java-version }}
          cache: maven
          distribution: "adopt"

      - name: Run Selenium Tests and Generate Allure Report
        run: |
          mvn clean test -Denvironment=ip -Dtest=TestForTest

      - name: Get Allure history (Windows)
        run: |
          git clone --branch gh-pages --single-branch --depth 1 https://github.com/your-username/your-repo.git gh-pages

      - name: Allure Report action from marketplace (Windows)
        run: |
          allure generate allure-results -o allure-report
          cp -r allure-report/* gh-pages/allure-report
          cp -r allure-results/history gh-pages/allure-history

      - name: Run PowerShell script to parse Allure report and set environment variable
        shell: powershell
        run: |
          # Replace the script command with your actual PowerShell script or tool
          # Example PowerShell script (replace with actual parsing logic):
          $TEST_CASE_FAILED = Get-Content allure-results/widgets/summary.json | ConvertFrom-Json | Select-Object -ExpandProperty data | Where-Object { $_.statistic == "failed" }
          if ($TEST_CASE_FAILED) {
            Write-Host "TEST_CASE_FAILED=true"
          } else {
            Write-Host "TEST_CASE_FAILED=false"
          }

          # Set the environment variable for later use
          Write-Host "##vso[task.setvariable variable=TEST_CASE_FAILED;isOutput=true]$TEST_CASE_FAILED"

      - name: Deploy report to Github Pages (Windows)
        run: |
               git add gh-pages
               git commit -m "Update Allure report"
               git push origin gh-pages
               ALLURE_REPORT_LINK=$(echo "https://testteam2023.github.io/A_M/allure-report")
               echo "::set-output name=allure_report_link::${ALLURE_REPORT_LINK}"

  notify:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Send email on test failure
        if: env.TEST_CASE_FAILED == 'true'
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: ${{ secrets.EMAIL_SERVER }}
          server_port: ${{ secrets.EMAIL_PORT }}
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: 'Selenium Test Failure Notification'
          body: |
            The Selenium tests have failed. Please check the workflow for details.
          Allure Report: [Link to Allure Report](${{ steps.mail.outputs.allure_report_link }})

          to: 'aabdelaziz@azka.com'
          from: 'azkatestingteam@gmail.com'

      - name: Send email on test success
        if: env.TEST_CASE_FAILED != 'true'
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: ${{ secrets.EMAIL_SERVER }}
          server_port: ${{ secrets.EMAIL_PORT }}
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: 'Selenium Test Success Notification with Allure Report'
          body: |
            The Selenium tests have passed successfully.
            Allure Report: [Link to Allure Report](${{ steps.mail.outputs.allure_report_link }})
          to: 'ahmedali@azka.com,aabdelaziz@azka.com'
          from: 'azkatestingteam@gmail.com'
