name: Run Selenium Test

on:
  push:
    branches: ["master"]
  schedule:
    - cron: "0 8 * * 0-4"  # Run at 10:00 AM from Sunday to Thursday

jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: "21"
          cache: maven
          distribution: "adopt"

      - name: Set up Edge browser
        uses: browser-actions/setup-edge@latest

      - name: Run Selenium Tests and Generate Report
        run: |
          mvn clean test -Denvironment=ip -Dbrowser=edge
          exit_code=$?
          if [ $exit_code -ne 0 ]; then
            echo "Tests failed with exit code $exit_code."
            exit $exit_code
          fi
      - name: Archive artifacts
        id: generate-report
        uses: actions/upload-artifact@v2
        with:
          name: test-reports
          path: target/surefire-reports

  send-email:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: test-reports
          path: target/surefire-reports

      - name: Set up email content
        id: set-email-content
        run: echo "::set-output name=email-body::<p>Dear Eng. Ahmed, The Selenium test results are attached. Please find the attached HTML report.</p>"

      - name: Send email on success
        if: success()
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: ${{ secrets.EMAIL_SERVER }}
          server_port: ${{ secrets.EMAIL_PORT }}
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "Khadem Store Test Results (Pass)"
          to: "aabdelaziz@azka.com"
          from: "azkatestingteam@gmail.com"
          content_type: "text/html"
          body: ${{ steps.set-email-content.outputs.email-body }}
          attachments: target/surefire-reports/emailable-report.html

      - name: Send email on failure
        if: failure()
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: ${{ secrets.EMAIL_SERVER }}
          server_port: ${{ secrets.EMAIL_PORT }}
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "Khadem Store Test Results (Fail)"
          to: "ahmed_abdelaziz99998@yahoo.com"
          from: "azkatestingteam@gmail.com"
          content_type: "text/html"
          body: ${{ steps.set-email-content.outputs.email-body }}
          attachments: target/surefire-reports/emailable-report.html
