name: Run Selenium and Allure Tests

on:
  push:
    branches: ["master"]
  schedule:
    - cron: "0 8 * * 0-4"  # Run at 10:00 AM from Sunday to Thursday

jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: "21"
          cache: maven
          distribution: "adopt"

      - name: Set up Chrome browser
        uses: browser-actions/setup-chrome@latest

      - name: Run Selenium Tests and Generate Allure Report
        run: |
          mvn clean test -Denvironment=ip -Dtest=TestForTest
          # Generate Allure report
          mvn allure:report
          # Copy the generated Allure report to a separate directory
          mkdir -p allure-results
          cp -R target/allure-results allure-results
        continue-on-error: true

      - name: Archive Allure results
        uses: actions/upload-artifact@v2
        with:
          name: allure-results
          path: allure-results

  generate-allure-report:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Download Allure results
        uses: actions/download-artifact@v2
        with:
          name: allure-results
          path: allure-results

      - name: Generate Allure report
        uses: simple-elf/allure-report-action@master
        with:
          allure_results: allure-results
          allure_report: allure-report
          allure_history: allure-history

      - name: Deploy Allure report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history

  send-email:
    needs: generate-allure-report
    runs-on: ubuntu-latest
    steps:
      - name: Download Allure report
        uses: actions/download-artifact@v2
        with:
          name: allure-results
          path: allure-results

      - name: Check Allure test results
        id: check-allure-results
        run: |
          failures=$(grep -c 'failures="1"' allure-results/widgets/summary.json || true)
          echo "::set-output name=allure-failures::$failures"

      - name: Send email on failure (Allure)
        if: ${{ steps.check-allure-results.outputs.allure-failures != '0' }}
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: ${{ secrets.EMAIL_SERVER }}
          server_port: ${{ secrets.EMAIL_PORT }}
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          to: "azkatestingteam@gmail.com"
          from: "azkatestingteam@gmail.com"
          subject: "Khadem Store Allure Test Results - Failure"
          body: |
            <p>
            Dear Eng. Ahmed,
            The Allure test results indicate a failure. Please review the attached Allure report.
            </p>
          attachments: allure-results/index.html

      - name: Send email on success (Allure)
        if: ${{ steps.check-allure-results.outputs.allure-failures == '0' }}
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: ${{ secrets.EMAIL_SERVER }}
          server_port: ${{ secrets.EMAIL_PORT }}
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          to: "aabdelaziz@azka.com"
          from: "azkatestingteam@gmail.com"
          subject: "Khadem Store Allure Test Results - Success"
          body: |
            <p>
            Dear Eng. Ahmed,
            The Allure test results indicate a success. Please find the attached Allure report.
            </p>
          attachments: allure-results/index.html
