name: Selenium Test and Email

on:
  push:
    branches: ["master"]
  schedule:
    - cron: "0 8 * * 0-4"  # Run at 10:00 AM from Sunday to Thursday

jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: "21"
          cache: maven
          distribution: "adopt"

      - name: Set up Edge browser
        uses: browser-actions/setup-edge@latest

      - name: Run Selenium Tests and Generate Report
        run: |
          mvn clean test -Denvironment=ip -Dtest=ItemRecievedRecordTest -Dbrowser=edge || true
      - name: Archive artifacts
        id: generate-report
        uses: actions/upload-artifact@v2
        with:
          name: test-reports
          path: target/surefire-reports

  send-email:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: test-reports
          path: target/surefire-reports

      - name: Send Email using action-send-mail (Success)
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: ${{ secrets.EMAIL_SERVER }}
          server_port: ${{ secrets.EMAIL_PORT }}
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "Khadem Store Test Results"
          from: "azkatestingteam@gmail.com"
          content_type: "text/html"
          body: |
            <p>
            Dear Eng. Ahmed,
            The Selenium test results are attached. Please find the attached HTML report.
            </p>
          attachments: target/surefire-reports/emailable-report.html
          to: ${{ needs.test.result == 'success' && secrets.EMAIL_PASS || secrets.EMAIL_FAIL }}

      - name: Send Email using action-send-mail (Failure)
        run: |
          EMAIL_FAIL_ARRAY=($(echo "${{ secrets.EMAIL_FAIL }}" | tr ',' '\n'))
          for email in "${EMAIL_FAIL_ARRAY[@]}"; do
            echo "Sending failure email to: $email"
            action-send-mail \
              --server-address ${{ secrets.EMAIL_SERVER }} \
              --server-port ${{ secrets.EMAIL_PORT }} \
              --username ${{ secrets.EMAIL_USERNAME }} \
              --password ${{ secrets.EMAIL_PASS }} \
              --subject "Khadem Store Test Results (Failure)" \
              --from "azkatestingteam@gmail.com" \
              --content-type "text/html" \
              --body "Dear Eng. Ahmed, The Selenium test results indicate a failure. Please review the attached HTML report." \
              --attachments target/surefire-reports/emailable-report.html \
              --to $email
          done
        env:
          TO_EMAIL_FAILURE: ${{ secrets.EMAIL_FAIL }}
