name: Run Selenium Test

on:
  push:
    branches: ["master"]
  schedule:
    - cron: "0 8 * * 0-4"  # Run at 10:00 AM from Sunday to Thursday

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: "21"  # Choose the appropriate Java version for your project
          cache: maven
          distribution: "adopt"

      - name: Set up Chrome browser
        uses: browser-actions/setup-chrome@latest

      - name: Run Selenium Tests and Generate Allure Report
        run: |
          mvn clean test -Denvironment=ip -Dtest=TestForTest

      - name: Get Allure history
        uses: actions/checkout@v2
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Allure Report action from marketplace
        uses: simple-elf/allure-report-action@master
        id: allure-report
        with:
          allure_results: allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history

      - name: Deploy report to Github Pages
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history
      - name: Set TEST_CASE_FAILED variable
        id: set-test-failed
        run: |
            if grep -q "status=\"failed\"" allure-results/*.xml; then
              echo "TEST_CASE_FAILED=true" >> $GITHUB_ENV
            else
              echo "TEST_CASE_FAILED=false" >> $GITHUB_ENV
            fi    


  notify:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Send email on test failure
        if: env.TEST_CASE_FAILED == 'true'
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: ${{ secrets.EMAIL_SERVER }}
          server_port: ${{ secrets.EMAIL_PORT }}
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: 'Selenium Test Failure Notification'
          body: |
            The Selenium tests have failed. Please check the workflow for details.
            Allure Report: [Link to Allure Report](${{ steps.mail.outputs.allure_report_link }})

          to: 'aabdelaziz@azka.com'
          from: 'azkatestingteam@gmail.com'

      - name: Send email on test success
        if: env.TEST_CASE_FAILED != 'true'
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: ${{ secrets.EMAIL_SERVER }}
          server_port: ${{ secrets.EMAIL_PORT }}
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: 'Selenium Test Success Notification with Allure Report'
          body: |
            The Selenium tests have passed successfully.
            Allure Report: [Link to Allure Report](${{ steps.mail.outputs.allure_report_link }})
          to: 'ahmedali@azka.com,aabdelaziz@azka.com'
          from: 'azkatestingteam@gmail.com'
